[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier.Views")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier.ViewModels")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier.Models")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier.Interfaces")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Readier.Controls")]
